#!/usr/bin/env python3
"""
Curator-supervised multimodal wheat disease severity classification.

Original code generated by:
    Saman Maghsoudi, Liverpool Hope University

Purpose
-------
This script trains and evaluates a multimodal image-text model for classifying
wheat disease severity from literature-derived leaf assay images and associated
text. The text input combines assay labels and figure captions.

The workflow was developed as a small proof-of-concept study to explore whether
image and text information from published plant pathology studies can support
phenotype evidence extraction and biocuration.

Important limitation
--------------------
This code was developed for a small dataset of 40 image-caption samples. It is
not intended as a deployable diagnostic system and should not be used for disease
diagnosis in field, glasshouse, or clinical settings.
"""

from __future__ import annotations

import argparse
import itertools
import json
import os
import random
import warnings
from collections import Counter
from pathlib import Path
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.models as models
import torchvision.transforms as transforms
from imblearn.under_sampling import TomekLinks
from PIL import Image
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from transformers import BertModel, BertTokenizer

warnings.filterwarnings(
    "ignore",
    message="The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.",
)

# Text augmentation uses WordNet synonyms.
# Make sure WordNet is available before running:
# python -m nltk.downloader wordnet omw-1.4
from nltk.corpus import wordnet

CLASS_LABELS = ["low", "high", "medium", "none"]
NUM_CLASSES = len(CLASS_LABELS)


def set_random_seed(seed: int) -> None:
    """Set random seeds to make repeated runs as reproducible as possible."""
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


class RandomSynonymAugment:
    """
    Simple text augmentation by replacing a small number of words with synonyms.

    This is used only for training data. Validation text is not augmented.
    Because biological captions may contain specialist terms, synonym replacement
    should be interpreted cautiously and kept conservative.
    """

    def __init__(self, p: float = 0.5, n_aug: int = 1):
        self.p = p
        self.n_aug = n_aug

    def __call__(self, text: str) -> str:
        if random.random() > self.p:
            return text
        words = text.split()
        if not words:
            return text
        n_to_replace = random.randint(1, self.n_aug)
        indices_to_replace = random.sample(range(len(words)), k=min(n_to_replace, len(words)))
        new_words = words[:]
        for idx in indices_to_replace:
            synonyms = self._get_synonyms(words[idx])
            if synonyms:
                new_words[idx] = random.choice(list(synonyms))
        return " ".join(new_words)

    @staticmethod
    def _get_synonyms(word: str) -> set[str]:
        synonyms = set()
        for synset in wordnet.synsets(word):
            for lemma in synset.lemmas():
                lemma_name = lemma.name().replace("_", " ")
                if lemma_name.lower() != word.lower():
                    synonyms.add(lemma_name)
        return synonyms


class MultimodalDataset(Dataset):
    """
    Dataset containing paired image and text inputs.

    Each sample contains one wheat leaf assay image, text made from assay label
    plus caption, and one severity label.
    """

    def __init__(self, image_paths, texts, labels, image_transform=None, text_transform=None):
        self.image_paths = image_paths
        self.texts = texts
        self.labels = labels
        self.image_transform = image_transform
        self.text_transform = text_transform

    def __len__(self) -> int:
        return len(self.image_paths)

    def __getitem__(self, idx: int):
        image = Image.open(self.image_paths[idx]).convert("RGB")
        image_tensor = self.image_transform(image) if self.image_transform else transforms.ToTensor()(image)
        text_str = self.texts[idx]
        if self.text_transform:
            text_str = self.text_transform(text_str)
        return image_tensor, text_str, self.labels[idx]


class MultimodalModel(nn.Module):
    """
    Multimodal model combining image and text features.

    Image branch: pre-trained GoogLeNet extracts visual features from assay images.
    Text branch: BERT-base-uncased extracts text features from assay labels and captions.
    Fusion: image and text vectors are projected, concatenated and classified.

    Biological rationale: biocurators interpret assay figures together with
    captions and experimental descriptions, not as isolated images.
    """

    def __init__(self, num_classes: int = 4, fine_tune_bert: bool = True):
        super().__init__()
        googlenet_weights = models.GoogLeNet_Weights.IMAGENET1K_V1
        self.googlenet = models.googlenet(weights=googlenet_weights)
        self.googlenet.fc = nn.Identity()
        self.bert = BertModel.from_pretrained("bert-base-uncased")
        for _, param in self.bert.named_parameters():
            param.requires_grad = fine_tune_bert
        hidden_size = 128
        self.image_fc = nn.Sequential(nn.Linear(1024, hidden_size), nn.BatchNorm1d(hidden_size), nn.ReLU(), nn.Dropout(0.5))
        self.text_fc = nn.Sequential(nn.Linear(768, hidden_size), nn.BatchNorm1d(hidden_size), nn.ReLU(), nn.Dropout(0.5))
        self.combined_fc = nn.Sequential(nn.Linear(hidden_size * 2, 128), nn.BatchNorm1d(128), nn.ReLU(), nn.Dropout(0.5), nn.Linear(128, num_classes))

    def forward(self, images, input_ids, attention_mask):
        img_feats = self.googlenet(images)
        img_out = self.image_fc(img_feats)
        text_outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_embed = text_outputs.last_hidden_state[:, 0, :]
        txt_out = self.text_fc(cls_embed)
        combined = torch.cat([img_out, txt_out], dim=1)
        return self.combined_fc(combined)


def get_image_transforms():
    transform_train = transforms.Compose([
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomVerticalFlip(p=0.5),
        transforms.RandomRotation(15),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
        transforms.RandomResizedCrop((224, 224), scale=(0.8, 1.0)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    transform_val = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    return transform_train, transform_val


def combine_text(row: pd.Series) -> str:
    assay_part = str(row["assay_label"]) if pd.notna(row["assay_label"]) else ""
    caption_part = str(row["caption"]) if pd.notna(row["caption"]) else ""
    return f"{assay_part} - {caption_part}" if caption_part.strip() else assay_part


def find_image_file_recursive(filename: str, root_dir: Path) -> Optional[str]:
    filename_lower = filename.lower()
    for dirpath, _, files in os.walk(root_dir):
        for file_name in files:
            if file_name.lower() == filename_lower:
                return str(Path(dirpath) / file_name)
    return None


def load_dataset(excel_file: Path, image_base_dir: Path):
    """
    Load metadata from Excel and return image paths, text strings and label indices.

    Expected sheets:
    - Figures: pmid, filename, assay_label, label
    - Captions: pmid, caption
    """
    df_figures = pd.read_excel(excel_file, sheet_name="Figures")
    df_captions = pd.read_excel(excel_file, sheet_name="Captions")
    df_merged = df_figures.merge(df_captions, on="pmid", how="left", suffixes=("", "_cap"))
    df_merged["text_data"] = df_merged.apply(combine_text, axis=1)
    image_paths, texts, labels = [], [], []
    for idx, row in df_merged.iterrows():
        found_path = find_image_file_recursive(str(row["filename"]), image_base_dir)
        if found_path is None:
            print(f"Warning: no image found for '{row['filename']}'. Skipping row {idx}.")
            continue
        label_str = str(row["label"]).strip().lower()
        if label_str not in CLASS_LABELS:
            print(f"Warning: unexpected label '{label_str}'. Skipping row {idx}.")
            continue
        image_paths.append(found_path)
        texts.append(str(row["text_data"]))
        labels.append(CLASS_LABELS.index(label_str))
    print(f"Total images used: {len(labels)}")
    label_counts = Counter(labels)
    print("Class distribution:", {CLASS_LABELS[c]: label_counts[c] for c in label_counts})
    return image_paths, texts, labels


def save_confusion_matrix(confusion: np.ndarray, output_path: Path) -> None:
    plt.figure(figsize=(6, 5))
    plt.imshow(confusion, interpolation="nearest", cmap=plt.cm.Blues)
    plt.title("Combined Confusion Matrix (All Folds)")
    plt.colorbar()
    tick_marks = np.arange(NUM_CLASSES)
    plt.xticks(tick_marks, CLASS_LABELS, rotation=45)
    plt.yticks(tick_marks, CLASS_LABELS)
    thresh = confusion.max() / 2.0
    for i, j in itertools.product(range(confusion.shape[0]), range(confusion.shape[1])):
        plt.text(j, i, confusion[i, j], horizontalalignment="center", color="white" if confusion[i, j] > thresh else "black")
    plt.xlabel("Predicted label")
    plt.ylabel("True label")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()


def train_and_evaluate(args: argparse.Namespace) -> dict:
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    set_random_seed(args.random_seed)
    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")
    print(f"Using device: {device}")
    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
    transform_train, transform_val = get_image_transforms()
    text_transform_train = RandomSynonymAugment(p=0.5, n_aug=2)
    image_paths, texts, labels = load_dataset(Path(args.excel_file), Path(args.image_base_dir))
    if len(labels) == 0:
        raise ValueError("No labelled image-text samples were loaded.")
    skf = StratifiedKFold(n_splits=args.k_folds, shuffle=True, random_state=args.random_seed)
    acc_scores, prec_scores, rec_scores, f1_scores = [], [], [], []
    combined_cm = np.zeros((NUM_CLASSES, NUM_CLASSES), dtype=np.int32)
    global_best_val_loss = float("inf")
    best_model_state = None

    for fold_idx, (train_idx, val_idx) in enumerate(skf.split(image_paths, labels), 1):
        print(f"\n----- Fold {fold_idx} -----")
        train_image_full = [image_paths[i] for i in train_idx]
        train_texts_full = [texts[i] for i in train_idx]
        train_labels_full = [labels[i] for i in train_idx]

        # Tomek Links is included as an additional undersampling step.
        # In this small dataset it may remove few or no samples in some folds.
        X_indices = np.array(range(len(train_labels_full))).reshape(-1, 1)
        y_labels = np.array(train_labels_full)
        X_resampled, _ = TomekLinks(sampling_strategy="auto").fit_resample(X_indices, y_labels)
        resampled_indices = X_resampled.flatten()
        train_image = [train_image_full[i] for i in resampled_indices]
        train_texts = [train_texts_full[i] for i in resampled_indices]
        train_labels = [train_labels_full[i] for i in resampled_indices]
        print(f"Fold {fold_idx} - original samples: {len(train_labels_full)}, after Tomek Links: {len(train_labels)}")
        print("Class distribution after Tomek Links:", {CLASS_LABELS[c]: count for c, count in Counter(train_labels).items()})

        val_image = [image_paths[i] for i in val_idx]
        val_texts = [texts[i] for i in val_idx]
        val_labels = [labels[i] for i in val_idx]
        train_ds = MultimodalDataset(train_image, train_texts, train_labels, image_transform=transform_train, text_transform=text_transform_train)
        val_ds = MultimodalDataset(val_image, val_texts, val_labels, image_transform=transform_val, text_transform=None)
        class_sample_count = Counter(train_labels)
        weights_per_class = {c: 1.0 / count for c, count in class_sample_count.items()}
        samples_weight = [weights_per_class[label] for label in train_labels]
        sampler = WeightedRandomSampler(samples_weight, num_samples=len(samples_weight), replacement=True)
        # drop_last avoids a final batch of size 1, which would break BatchNorm1d in training mode.
        train_loader = DataLoader(train_ds, batch_size=args.batch_size, sampler=sampler, num_workers=args.num_workers, drop_last=True)
        val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers)
        model = MultimodalModel(num_classes=NUM_CLASSES, fine_tune_bert=args.fine_tune_bert).to(device)
        criterion = nn.CrossEntropyLoss(label_smoothing=args.label_smoothing)
        optimizer = optim.AdamW(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
        scheduler = optim.lr_scheduler.OneCycleLR(optimizer, max_lr=args.learning_rate, steps_per_epoch=len(train_loader), epochs=args.epochs)
        best_val_loss = float("inf")

        for epoch in range(args.epochs):
            model.train()
            running_loss = 0.0
            for imgs, txts, lbls in train_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)
                encoded = tokenizer(txts, return_tensors="pt", padding=True, truncation=True, max_length=args.max_text_length).to(device)
                optimizer.zero_grad()
                outputs = model(imgs, encoded["input_ids"], encoded["attention_mask"])
                loss = criterion(outputs, lbls)
                loss.backward()
                optimizer.step()
                scheduler.step()
                running_loss += loss.item()
            train_loss = running_loss / len(train_loader)
            model.eval()
            val_loss = 0.0
            with torch.no_grad():
                for imgs, txts, lbls in val_loader:
                    imgs, lbls = imgs.to(device), lbls.to(device)
                    encoded = tokenizer(txts, return_tensors="pt", padding=True, truncation=True, max_length=args.max_text_length).to(device)
                    outputs = model(imgs, encoded["input_ids"], encoded["attention_mask"])
                    val_loss += criterion(outputs, lbls).item()
            val_loss /= len(val_loader)
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                if val_loss < global_best_val_loss:
                    global_best_val_loss = val_loss
                    best_model_state = model.state_dict()
                    print(f"New global best model found (fold {fold_idx}, epoch {epoch + 1}) val_loss={val_loss:.4f}")
            print(f"Fold {fold_idx} Epoch [{epoch + 1}/{args.epochs}] Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")

        model.eval()
        all_outputs, all_labels = [], []
        with torch.no_grad():
            for imgs, txts, lbls in val_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)
                encoded = tokenizer(txts, return_tensors="pt", padding=True, truncation=True, max_length=args.max_text_length).to(device)
                outputs = model(imgs, encoded["input_ids"], encoded["attention_mask"])
                all_outputs.append(outputs.cpu())
                all_labels.append(lbls.cpu())
        all_outputs = torch.cat(all_outputs)
        all_labels = torch.cat(all_labels)
        _, preds = torch.max(all_outputs, 1)
        acc = accuracy_score(all_labels, preds)
        prec = precision_score(all_labels, preds, average="weighted", zero_division=0)
        rec = recall_score(all_labels, preds, average="weighted", zero_division=0)
        f1 = f1_score(all_labels, preds, average="weighted", zero_division=0)
        acc_scores.append(acc)
        prec_scores.append(prec)
        rec_scores.append(rec)
        f1_scores.append(f1)
        print(f"Fold {fold_idx} Metrics: Accuracy={acc * 100:.2f}%, Precision={prec:.4f}, Recall={rec:.4f}, F1={f1:.4f}")
        combined_cm += confusion_matrix(all_labels, preds, labels=range(NUM_CLASSES))

    best_model_path = output_dir / args.best_model_name
    if best_model_state is not None:
        torch.save(best_model_state, best_model_path)
        print(f"\nSaved best model state with val loss {global_best_val_loss:.4f} to {best_model_path}")

    results = {
        "accuracy_mean": float(np.mean(acc_scores)),
        "accuracy_std": float(np.std(acc_scores)),
        "precision_mean": float(np.mean(prec_scores)),
        "precision_std": float(np.std(prec_scores)),
        "recall_mean": float(np.mean(rec_scores)),
        "recall_std": float(np.std(rec_scores)),
        "f1_mean": float(np.mean(f1_scores)),
        "f1_std": float(np.std(f1_scores)),
        "combined_confusion_matrix": combined_cm.tolist(),
        "class_labels": CLASS_LABELS,
        "n_samples": len(labels),
        "class_distribution": {CLASS_LABELS[c]: count for c, count in Counter(labels).items()},
        "k_folds": args.k_folds,
        "random_seed": args.random_seed,
        "fine_tune_bert": args.fine_tune_bert,
    }
    print("\n--- Cross-validation results ---")
    print(f"Accuracy: {results['accuracy_mean'] * 100:.2f}% (±{results['accuracy_std'] * 100:.2f}%)")
    print(f"Precision: {results['precision_mean']:.4f} (±{results['precision_std']:.4f})")
    print(f"Recall: {results['recall_mean']:.4f} (±{results['recall_std']:.4f})")
    print(f"F1-score: {results['f1_mean']:.4f} (±{results['f1_std']:.4f})")
    print("\nCombined confusion matrix:")
    print(combined_cm)
    with open(output_dir / "cross_validation_results.json", "w", encoding="utf-8") as handle:
        json.dump(results, handle, indent=2)
    save_confusion_matrix(combined_cm, output_dir / "combined_confusion_matrix_bert_entity.png")
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train and evaluate a multimodal image-text model for wheat disease severity classification.")
    parser.add_argument("--excel-file", required=True, help="Path to Excel metadata file containing Figures and Captions sheets.")
    parser.add_argument("--image-base-dir", required=True, help="Path to folder containing extracted assay images.")
    parser.add_argument("--output-dir", default="outputs", help="Directory where outputs will be saved.")
    parser.add_argument("--best-model-name", default="best_overall_model_bert_entity.pth")
    parser.add_argument("--k-folds", type=int, default=5)
    parser.add_argument("--random-seed", type=int, default=40)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--learning-rate", type=float, default=1e-4)
    parser.add_argument("--weight-decay", type=float, default=0.05)
    parser.add_argument("--label-smoothing", type=float, default=0.1)
    parser.add_argument("--max-text-length", type=int, default=128)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--fine-tune-bert", action=argparse.BooleanOptionalAction, default=True, help="Fine-tune BERT during training. Use --no-fine-tune-bert to freeze BERT.")
    parser.add_argument("--cpu", action="store_true", help="Force CPU use even when CUDA is available.")
    return parser.parse_args()


if __name__ == "__main__":
    train_and_evaluate(parse_args())
